name: Deploy Supabase

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Set secrets
        run: |
          supabase secrets set GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}

      - name: Push database migrations
        run: supabase db push --ignore-destructive

      - name: Deploy Edge Functions
        run: supabase functions deploy documents



